services:
  php:
    container_name: apirone_sdk_php_apache
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        GID: 1000
        UID: 1000
    volumes:
      - ./examples:/var/www/html/
      - ./src:/var/www/src/
      - ./src/assets:/var/www/html/assets
      - ./vendor:/var/www/vendor
      - ./docker/storage:/var/www/storage/
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./composer.json:/var/www/composer.json
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=9003"
      XDEBUG_MODE: develop,debug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80

  ##
  # To use mysql or postgresql container, uncomment the desired one
  #
  # # Maria DB container
  # db_mysql:
  #   container_name: apirone_sdk_php_mysql
  #   image: mariadb:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: apirone
  #   volumes:
  #     - ./docker/data/mysql:/var/lib/mysql
  #     - ./docker/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  #   ports:
  #     - '3306:3306'

  # # PostgreSQL DB container
  # db_pgsql:
  #   container_name: apirone_sdk_php_pgsql
  #   image: postgres
  #   # set shared memory limit when using docker compose
  #   shm_size: 128mb
  #   # or set shared memory limit when deploy via swarm stack
  #   #volumes:
  #   #  - type: tmpfs
  #   #    target: /dev/shm
  #   #    tmpfs:
  #   #      size: 134217728 # 128*2^20 bytes = 128Mb
  #   environment:
  #     POSTGRES_PASSWORD: apirone
  #     POSTGRES_USER: apirone
  #     POSTGRES_DB: apirone
  #   ports:
  #     - "5432:5432"
